/*
 * Simplify3DDialect.h
 *
 *  Created on: Jan 15, 2016
 *      Author: eai
 */

#ifndef SIMPLIFY3DDIALECT_H_
#define SIMPLIFY3DDIALECT_H_

#include "SlicerDialect.h"

/*

; G-Code generated by Simplify3D(R) Version 3.0.0
; oct 15, 2015 at 3:38:29
; Settings Summary
;   processName,Process1
;   applyToModels,ironman_bust
;   profileName,Default (modified)
;   profileVersion,2015-05-01 08:00:00
;   baseProfile,
;   printMaterial,
;   printQuality,
;   printExtruders,
;   extruderName,Primary Extruder
;   extruderToolheadNumber,0
;   extruderDiameter,0.4
;   extruderAutoWidth,0
;   extruderWidth,0.4
;   extrusionMultiplier,1
;   extruderUseRetract,1
;   extruderRetractionDistance,1.2
;   extruderExtraRestartDistance,0
;   extruderRetractionZLift,0
;   extruderRetractionSpeed,1800
;   extruderUseCoasting,0
;   extruderCoastingDistance,0.2
;   extruderUseWipe,0
;   extruderWipeDistance,5
;   primaryExtruder,0
;   layerHeight,0.1
;   topSolidLayers,4
;   bottomSolidLayers,2
;   perimeterOutlines,3
;   printPerimetersInsideOut,1
;   startPointOption,3
;   startPointOriginX,175
;   startPointOriginY,0
;   startPointOriginZ,200
;   sequentialIslands,0
;   spiralVaseMode,0
;   firstLayerHeightPercentage,150
;   firstLayerWidthPercentage,100
;   firstLayerUnderspeed,0.6
;   useRaft,0
;   raftExtruder,0
;   raftLayers,3
;   raftOffset,3
;   raftSeparationDistance,0.14
;   raftInfill,85
;   disableRaftBaseLayers,0
;   useSkirt,1
;   skirtExtruder,0
;   skirtLayers,1
;   skirtOutlines,2
;   skirtOffset,5
;   usePrimePillar,0
;   primePillarExtruder,999
;   primePillarWidth,12
;   primePillarLocation,7
;   primePillarSpeedMultiplier,1
;   useOozeShield,0
;   oozeShieldExtruder,999
;   oozeShieldOffset,2
;   oozeShieldOutlines,1
;   oozeShieldSidewallShape,1
;   oozeShieldSidewallAngle,30
;   oozeShieldSpeedMultiplier,1
;   infillExtruder,0
;   internalInfillPattern,Rectilinear
;   externalInfillPattern,Rectilinear
;   infillPercentage,15
;   outlineOverlapPercentage,15
;   infillExtrusionWidthPercentage,100
;   minInfillLength,5
;   infillLayerInterval,1
;   infillAngles,45,-45
;   overlapInfillAngles,0
;   generateSupport,1
;   supportExtruder,0
;   supportInfillPercentage,10
;   supportExtraInflation,0
;   denseSupportLayers,0
;   denseSupportInfillPercentage,70
;   supportLayerInterval,1
;   supportHorizontalPartOffset,0.3
;   supportUpperSeparationLayers,1
;   supportLowerSeparationLayers,1
;   supportType,0
;   supportGridSpacing,4
;   maxOverhangAngle,65
;   supportAngles,0
;   temperatureName,Extrusor,Cama
;   temperatureNumber,0,0
;   temperatureSetpointCount,1,1
;   temperatureSetpointLayers,1,1
;   temperatureSetpointTemperatures,210,70
;   temperatureStabilizeAtStartup,1,1
;   temperatureHeatedBed,0,1
;   temperatureRelayBetweenLayers,0,0
;   temperatureRelayBetweenLoops,0,0
;   fanLayers,1,2
;   fanSpeeds,0,100
;   blipFanToFullPower,0
;   adjustSpeedForCooling,1
;   minSpeedLayerTime,15
;   minCoolingSpeedSlowdown,20
;   increaseFanForCooling,0
;   minFanLayerTime,45
;   maxCoolingFanSpeed,100
;   increaseFanForBridging,0
;   bridgingFanSpeed,100
;   use5D,1
;   relativeEdistances,0
;   allowEaxisZeroing,1
;   independentExtruderAxes,0
;   includeM10123,0
;   stickySupport,1
;   applyToolheadOffsets,0
;   gcodeXoffset,0
;   gcodeYoffset,0
;   gcodeZoffset,0
;   overrideMachineDefinition,0
;   machineTypeOverride,0
;   strokeXoverride,200
;   strokeYoverride,200
;   strokeZoverride,200
;   originOffsetXoverride,0
;   originOffsetYoverride,0
;   originOffsetZoverride,0
;   homeXdirOverride,-1
;   homeYdirOverride,-1
;   homeZdirOverride,-1
;   flipXoverride,1
;   flipYoverride,-1
;   flipZoverride,1
;   toolheadOffsets,0,0|0,0|0,0|0,0|0,0|0,0
;   overrideFirmwareConfiguration,0
;   firmwareTypeOverride,RepRap (Marlin/Repetier/Sprinter)
;   GPXconfigOverride,r2
;   baudRateOverride,115200
;   overridePrinterModels,0
;   printerModelsOverride
;   startingGcode,G28 ; home all axes
;   layerChangeGcode,
;   retractionGcode,
;   toolChangeGcode,
;   endingGcode,M104 S0 ; turn off extruder,M140 S0 ; turn off bed,M84 ; disable motors
;   createX3G,0
;   celebration,0
;   celebrationSong,Random Song
;   createMB5G,0
;   postProcessing,
;   defaultSpeed,3600
;   outlineUnderspeed,0.5
;   solidInfillUnderspeed,0.8
;   supportUnderspeed,0.8
;   rapidXYspeed,4800
;   rapidZspeed,1002
;   minBridgingArea,50
;   bridgingExtraInflation,0
;   bridgingExtrusionMultiplier,1
;   bridgingSpeedMultiplier,1
;   filamentDiameter,1.75
;   filamentPricePerKg,350
;   filamentDensity,1.25
;   useMinPrintHeight,0
;   minPrintHeight,0
;   useMaxPrintHeight,0
;   maxPrintHeight,0
;   useDiaphragm,0
;   diaphragmLayerInterval,20
;   robustSlicing,1
;   mergeAllIntoSolid,1
;   onlyRetractWhenCrossingOutline,1
;   retractBetweenLayers,1
;   useRetractionMinTravel,1
;   retractionMinTravel,10
;   retractWhileWiping,0
;   onlyWipeOutlines,0
;   avoidCrossingOutline,1
;   maxMovementDetourFactor,3
;   toolChangeRetractionDistance,12
;   toolChangeExtraRestartDistance,-0.5
;   toolChangeRetractionSpeed,600
;   allowThinWallGapFill,1
;   thinWallAllowedOverlapPercentage,10
;   horizontalSizeCompensation,0

End:
; Build Summary
;   Build time: 2 hours 15 minutes
;   Filament length: 4359.4 mm (4.36 m)
;   Plastic volume: 10485.70 mm^3 (10.49 cc)
;   Plastic weight: 13.11 g (0.03 lb)
;   Material cost: 4.59

 */

#define SIMPLIFY3D_INIT_HEADER "; G-Code generated by Simplify3D"

class Simplify3DDialect : public SlicerDialect {
public:
	Simplify3DDialect();
	virtual ~Simplify3DDialect();

	void parse_line(SlicingInformation* info, const char* line);
	// Simplify 3D has long headers. 7kbs should be enough.
	unsigned int get_header_len() {return 7*1024;};
	// 300 bytes should be enough.
	unsigned int get_footer_len() {return 300;};
	enum slicer_name get_slicer_name() {return SIMPLIFY3D;};

	static bool is_this_slicer_gcode(const char* line);
	static const unsigned int BYTES_TO_IDENTIFY_SLICER = 60; // Incomplete lines are discarded, so we must ensure the first line will be read
private:
	// b<i> is true if and only if t<i> is the temperature of the heated bed. Otherwise, it is an extruder temp.
	float t1;
	float t2;
	float t3;
	int b1;
	int b2;
	int b3;
	// whether TEMPERATURE_SETPOINT_TEMPERATURES_STRING was read
	bool temps_read;
	// whether TEMPERATURE_HEATED_BED_STRING was read
	bool hb_read;
};

#endif /* SIMPLIFY3DDIALECT_H_ */
