/*
 * Slic3rDialect.h
 *
 *  Created on: Jan 15, 2016
 *      Author: eai
 */

#ifndef SLIC3RDIALECT_H_
#define SLIC3RDIALECT_H_

#include "SlicerDialect.h"

/*
Sample Slic3r comments v0.9:
; generated by Slic3r 0.9.10b on 2014-08-27 at 11:04:43

; layer_height = 0.2
; perimeters = 2
; top_solid_layers = 3
; bottom_solid_layers = 3
; fill_density = 1
; perimeter_speed = 50
; infill_speed = 50
; travel_speed = 130
; nozzle_diameter = 0.4
; filament_diameter = 1.8
; extrusion_multiplier = 1
; perimeters extrusion width = 0.30mm
; infill extrusion width = 0.30mm
; solid infill extrusion width = 0.30mm
; top infill extrusion width = 0.30mm

End:
; filament used = 1540.1mm (3.9cm3)


Sample Slic3r comments v1.2.9
; generated by Slic3r 1.2.9 on 2016-01-15 at 14:47:52

; external perimeters extrusion width = 0.40mm
; perimeters extrusion width = 0.67mm
; infill extrusion width = 0.67mm
; solid infill extrusion width = 0.67mm
; top infill extrusion width = 0.67mm
; support material extrusion width = 0.40mm

End:
; filament used = 2371.5mm (5.7cm3)

; avoid_crossing_perimeters = 0
; bed_shape = 0x0,350x0,350x200,0x200
; bed_temperature = 0
; before_layer_gcode =
; bridge_acceleration = 0
; bridge_fan_speed = 100
; brim_width = 0
; complete_objects = 0
; cooling = 1
; default_acceleration = 0
; disable_fan_first_layers = 3
; duplicate_distance = 6
; end_gcode = M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors\n
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_colour = #FFFFFF
; filament_diameter = 1.75
; first_layer_acceleration = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 200%
; first_layer_speed = 30
; first_layer_temperature = 0
; gcode_arcs = 0
; gcode_comments = 0
; gcode_flavor = reprap
; infill_acceleration = 0
; infill_first = 0
; layer_gcode =
; max_fan_speed = 100
; max_print_speed = 80
; max_volumetric_speed = 0
; min_fan_speed = 35
; min_print_speed = 10
; min_skirt_length = 0
; notes =
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 1
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; perimeter_acceleration = 0
; post_process = /home/idlt/instalacion2/smoothieware/smoothie_merge/Smoothieware/postproc_slicer/kl_postproc.py
; pressure_advance = 0
; resolution = 0
; retract_before_travel = 2
; retract_layer_change = 1
; retract_length = 0.4
; retract_length_toolchange = 10
; retract_lift = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; skirt_distance = 6
; skirt_height = 1
; skirts = 1
; slowdown_below_layer_time = 5
; spiral_vase = 0
; standby_temperature_delta = -5
; start_gcode = G28 ; home all axes
; temperature = 0
; threads = 2
; toolchange_gcode =
; travel_speed = 130
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; vibration_limit = 0
; wipe = 0
; z_offset = 0
; dont_support_bridges = 1
; extrusion_width = 0
; first_layer_height = 0.3
; infill_only_where_needed = 0
; interface_shells = 0
; layer_height = 0.2
; raft_layers = 0
; seam_position = random
; support_material = 1
; support_material_angle = 0
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_spacing = 0
; support_material_interface_speed = 80%
; support_material_pattern = pillars
; support_material_spacing = 2.5
; support_material_speed = 40
; support_material_threshold = 0
; xy_size_compensation = 0
; bottom_solid_layers = 3
; bridge_flow_ratio = 1
; bridge_speed = 60
; external_fill_pattern = rectilinear
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 50%
; external_perimeters_first = 0
; extra_perimeters = 1
; fill_angle = 45
; fill_density = 20%
; fill_pattern = rectilinear
; gap_fill_speed = 20
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_overlap = 15%
; infill_speed = 40
; overhangs = 1
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 35
; perimeters = 4
; small_perimeter_speed = 30
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0
; solid_infill_speed = 20
; thin_walls = 1
; top_infill_extrusion_width = 0
; top_solid_infill_speed = 15
; top_solid_layers = 3

 */

#define SLIC3R_INIT_HEADER "; generated by Slic3r "

class Slic3rDialect : public SlicerDialect {
public:
	Slic3rDialect();
	virtual ~Slic3rDialect();

	void parse_line(SlicingInformation* info, const char* line);

	unsigned int get_header_len() {return 1024;};
	// 300 bytes should be enough for v0.9, but 1.2.9 requires far more characters.
	unsigned int get_footer_len() {return 4*1024;};
	enum slicer_name get_slicer_name() {return SLIC3R;};

	static bool is_this_slicer_gcode(const char* line);
	static const unsigned int BYTES_TO_IDENTIFY_SLICER = 60; // Incomplete lines are discarded, so we must ensure the first line will be read
};

#endif /* SLIC3RDIALECT_H_ */
